### ISSUE TITLE
Issue with catch-task-error sample

### ISSUE THREAD

**Issue by trissallan** [GoogleCloudPlatform/application-integration-samples#14]
**Describe the bug**
When running the test for the sample, catch-task-error, I do see that it fails because it is missing a third element.  However, it doesn't send the "error" email.  The logs show the data mapping task succeeding, but the whole integration fails (or shows as a "Canceled" status in the logs) due to the following error:

"Execution timeout, cancelled graph execution. Note any variable contains large data was failed to upload to GCS. Please try again."

**To Reproduce**
Follow directions as explained in the README

**Expected behavior**
According to the README, I expect to receive an email when the task errors because it can't find the 3rd element.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7797131-2a4c-402b-8959-a7e948d6e018)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome
 - Version130.0.6723.92 (Official Build) (64-bit)

**Comment by zhuht23** [comment]
Hi,

Sorry for the inconvenience. It seems like an issue from our side. We're actively working to fix this.

Haitao
GCP eng team

**Comment by trissallan** [comment]
Thanks @ssvaidyanathan!  Seems to be working for me now.
